name: Microservice CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: docker build -t flask-microservice .

      - name: Run tests inside container
        run: docker run --rm flask-microservice

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Tag and push image
        run: |
          docker tag flask-microservice ghcr.io/${{ secrets.GHCR_USERNAME }}/broken-image:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/broken-image:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deploy.yml
          
